function plot_ROE_comparison_with_cov(t, t_orbit, ROE1, ROE2, covariance, ...
    label1, label2, title_str2, fig_path2, title_str3, fig_path3)

    % plot_ROE_comparison(t, t_orbit, ROE1, ROE2, ...
    %    label1, label2, title_str2, fig_path2, title_str3, fig_path3);

    d_a1 = ROE1(:, 1);
    d_lambda1 = ROE1(:, 2);
    d_e_x1 = ROE1(:, 3);
    d_e_y1 = ROE1(:, 4);
    d_i_x1 = ROE1(:, 5);
    d_i_y1 = ROE1(:, 6);

    d_a2 = ROE2(:, 1);
    d_lambda2 = ROE2(:, 2);
    d_e_x2 = ROE2(:, 3);
    d_e_y2 = ROE2(:, 4);
    d_i_x2 = ROE2(:, 5);
    d_i_y2 = ROE2(:, 6);

    lw = 2.0;

    % === Time Histories ===
    time_orbits = t / t_orbit;

   figure('Color', 'w', 'Position', [100, 100, 800, 600]);

    axs = gobjects(6,1);
    labels = {'\delta a [m]', '\delta \lambda [m]', '\delta e_x [m]', ...
              '\delta e_y [m]', '\delta i_x [m]', '\delta i_y [m]'};
    
    ydata1 = {d_a1, d_lambda1, d_e_x1, d_e_y1, d_i_x1, d_i_y1};
    ydata2 = {d_a2, d_lambda2, d_e_x2, d_e_y2, d_i_x2, d_i_y2};
    
    legend_handles = gobjects(1,4);  % Preallocate for legend entries
    
    for k = 1:6
        axs(k) = subplot(3,2,k); hold on; grid on;
    
        std_1 = sqrt(covariance(:, k, k));
        std_2 = 2 * std_1;
    
        % 2σ Region (purple)
        h_fill2 = fill([time_orbits; flipud(time_orbits)], ...
             [ROE2(:, k) + std_2; flipud(ROE2(:, k) - std_2)], ...
             [0.85 0.75 1.0], ...      % light purple fill 
             'FaceAlpha', 0.3, ...
             'EdgeColor', 'none');
        
        % 1σ Region (red)
        h_fill1 = fill([time_orbits; flipud(time_orbits)], ...
             [ROE2(:, k) + std_1; flipud(ROE2(:, k) - std_1)], ...
             [1.0 0.6 0.6],'FaceAlpha', 0.4, ...
             'EdgeColor', 'none');
    
        % Plot lines
        h1 = plot(time_orbits, ydata1{k}, 'b', 'LineWidth', lw); % Ground Truth
        h2 = plot(time_orbits, ydata2{k}, 'r--', 'LineWidth', lw); % EKF
    
        xlabel('Number of orbits'); ylabel(labels{k});
    
        % Save legend handles only on first subplot
        if k == 1
            legend_handles = [h1, h2, h_fill2, h_fill1];
            legend(axs(k), legend_handles, ...
                {label1, label2, '2\sigma Region', '1\sigma Region'}, ...
                'Location', 'best');
        end
    end
    %sgtitle(title_str3);
    saveas(gcf, fig_path3);

    % === Time Histories with Covariance Bounds ===
    % time_orbits = t / t_orbit;
    % lw = 2.0;
    % axs = gobjects(6,1);
    % labels = {'\delta a [m]', '\delta \lambda [m]', '\delta e_x [m]', ...
    %           '\delta e_y [m]', '\delta i_x [m]', '\delta i_y [m]'};
    % 
    % % Overlay ROE2 with covariance bounds on the figure generated by plot_ROE_comparison
    % figure(gcf); % Bring the previous figure to focus
    % for k = 1:6
    %     subplot(3,2,k); hold on;
    %     % std = sqrt(covariance(:, k, k));
    %     % fill([time_orbits; flipud(time_orbits)], ...
    %     %     [ROE1(:, k) + std; flipud(ROE1(:, k) - std)], ...
    %     %     [0.7 0.85 1], 'FaceAlpha', 0.6, 'EdgeColor', [0.2 0.4 0.8], ...
    %     %     'DisplayName', '1\sigma Region');
    % 
    %     % plot(time_orbits, ROE1(:, k) + std, 'b:', 'LineWidth', 1.2, ...
    %     %     'DisplayName', ' + 1 sigma deviation');
    %     % plot(time_orbits, ROE1(:, k) - std, 'b:', 'LineWidth', 1.2, ... 
    %     %     'DisplayName', ' - 1 sigma deviation');
    % end
    %saveas(gcf, fig_path3);
    % Save a zoomed-in version focused on the first orbit (for convergence)
    for k = 1:6
        subplot(3,2,k);
        xlim([0, 1]);
    end
    zoomed_fig_path = strrep(fig_path3, '.png', '_zoomed.png');
    saveas(gcf, zoomed_fig_path);
end
