function plot_ROE_comparison_with_cov(t, t_orbit, ROE1, ROE2, covariance, ...
    label1, label2, title_str2, fig_path2, title_str3, fig_path3)

    plot_ROE_comparison(t, t_orbit, ROE1, ROE2, ...
        label1, label2, title_str2, fig_path2, title_str3, fig_path3);

    % === Time Histories with Covariance Bounds ===
    time_orbits = t / t_orbit;
    lw = 2.0;
    axs = gobjects(6,1);
    labels = {'\delta a [m]', '\delta \lambda [m]', '\delta e_x [m]', ...
              '\delta e_y [m]', '\delta i_x [m]', '\delta i_y [m]'};

    % Overlay ROE2 with covariance bounds on the figure generated by plot_ROE_comparison
    figure(gcf); % Bring the previous figure to focus
    for k = 1:6
        subplot(3,2,k); hold on;
        std = sqrt(covariance(:, k, k));
        plot(time_orbits, ROE2(:, k) + std, 'r:', 'LineWidth', 1.2, ...
            'DisplayName', 'One sigma deviation');
        plot(time_orbits, ROE2(:, k) - std, 'r:', 'LineWidth', 1.2, ...
            'DisplayName', 'One sigma deviation');
    end
end
