function [K] = hcw_integration_constants(initial_RTN, a)
    % Initial RTN includes the x, y, z, xdot, ydot, zdot that is also used
    % in relative orbital motion calculation
    % a is the semi-major axis of the chief
    global mu_earth;
    n = sqrt(mu_earth/a^3);
    A = [a*eye(3), zeros(3); zeros(3), a*n*eye(3)];
    t = 0;
    B = [1, sin(n*t), cos(n*t), 0, 0, 0; ...
        -3/2*n*t, 2*cos(n*t), -2*sin(n*t), 1, 0, 0; ...
        0, 0, 0, 0, sin(n*t), cos(n*t); ...
        0, cos(n*t), -sin(n*t), 0, 0, 0; ...
        -3/2, -2*sin(n*t), -2*cos(n*t), 0, 0, 0; ...
        0, 0, 0, 0, cos(n*t), -sin(n*t)];
    B = [1 0 1 0 0 0; ...
        0 2 0 1 0 0; ...
        0 0 0 0 0 1; ...
        0 1 0 0 0 0; ...
        -3/2 0 -2 0 0 0; ...
        0 0 0 0 1 0];
    total = A * B;
    K = total\initial_RTN;
end